on:
  push:
  workflow_dispatch:
  # Run every 2 hours from 12:00 to 20:00 everyday from June to September
  schedule: [{cron: '0 12,14,16,18,20 * 6-9 *'}]

name: scrape

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Fetch latest data
      run: Rscript scrape.R

    - uses: stefanzweifel/git-auto-commit-action@v5